name: appwrite_function
description: Appwrite Function
version: 1.0.0
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  http: ^1.1.0
dev_dependencies:
  test: any
  mockito: any
  build_runner: ^2.4.8